### ISSUE TITLE
quest 4661 can't see

### ISSUE THREAD

**Issue by yyhhrr** [classicdb/database#761] opened 2015-05-01 14:52 UTC
I collect the quest item,and go back to undercity,but when you click the object ,the log show nothing.
but when you change quest_temple PrevQuestId=0,i can see the gossip.maybe a core issues?

**Comment by Muehe** [comment] 2015-05-07 06:29
Tested this, can confirm it. There seems to be a problem with the negative ExclusiveGroup of the parent quest interfering with the negative PrevQuestId.

The quest line consists of two parent quests without prerequisites:

| Quest | PrevQuestId | NextQuestId | ExclusiveGroup |
| --- | --- | --- | --- |
| [A Sample of Slime... [4293] ](http://db.vanillagaming.org/?quest=4293) | 0 | 4642 | -4293 |
| [... and a Batch of Ooze [4294] ](http://db.vanillagaming.org/?quest=4294) | 0 | 4642 | -4293 |

Each of them have a child quest, that should become available once its parent quest is accepted:

| Quest | PrevQuestId | NextQuestId | ExclusiveGroup |
| --- | --- | --- | --- |
| [Testing for Corruption - Felwood [4661] ](http://db.vanillagaming.org/?quest=4661) | -4293 | 0 | 0 |
| [Testing for Impurities - Un'Goro Crater [4561] ](http://db.vanillagaming.org/?quest=4561) | -4294 | 0 | 0 |

The reason I'm guessing on ExclusiveGroup is that both child quests become available from their respective gameobject (174848/175265) once you have accepted both parent quests. The problem is that this behaviour breaks the quest line if you finish one parent quest before having enough quest items for both, because the child quests won't be available anymore. Same of course if you have only accepted one quest in the first place. Pretty sure this is not the intended behaviour.

Sadly, I have no idea if ExclusiveGroup is really the problem here and, assuming it is, if a DB sided solution can be found, because all entries seen above seem to be needed for the questline to work properly.

**Comment by cala** [comment] 2015-05-13 13:05
Thanks for all this research and data @Muehe 
I'll have a look at this. :+1:

**Comment by cala** [comment] 2015-05-14 13:34
I looked at it and @Muehe is 100% right on his analysis. I think this is a specific configuration and that it should be fixed core side: DB data are correct based on what they should be (see [wiki](https://github.com/cmangos/issues/wiki/quest_template)).
I'm closing the issue here. Thanks everyone.

**Closed as completed by cala** 2015-05-14 13:34 UTC
Labels: Quest, Non-functional
