### ISSUE TITLE
Class Paladin - Classlevelstats

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#791] opened 2015-07-21 02:58 UTC
Redo the armor for all paladins, it does not seem to be correct.

**Comment by Tobschinski** [comment] 2015-07-21 03:04
e.g. The most common armor value for 63 paladins is 3795 - the basearmor in the classlevelstats-table is 4637

**Comment by cala** [comment] 2015-07-21 11:50
Closed I'm afraid the problem is bigger than expected at first. See my answer in #790 
I close this issue to focus the discussion on the other one.

**Closed as completed by cala** 2015-07-21 11:50 UTC
