### ISSUE TITLE
Quest - When Smokey Sings, I Get Violent

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#299] opened 2014-03-08 03:17 UTC
Quest [When Smokey Sings, I Get Violent](http://www.wowhead.com/quest=6041/) seems to be broken, I do not get any progress. Quest-Item is spammable inside a structure. The Ziggurats will not be set on fire.

Since I do not know which parts will be handled by database or script yet, I open it here at first.

**Comment by cala** [comment] 2014-03-09 21:51
Thank you for this report. This issue sounds familiar. I'm sure I never fixed it and it is not amongst the open issues. Yet, I think I saw it reported somewhere. Anyway, I'll look at it.

**Comment by cala** [comment] 2014-12-22 08:27
Closing here: the issue is already [discussed on SD2](https://github.com/scriptdev2/scriptdev2/issues/121) repository and it sounds like it can't be done via DB due to spell targeting issue that need to be fixed elsewhere.

**Closed as completed by cala** 2014-12-22 08:27 UTC
Labels: Quest, Non-functional, Game Object

**Comment by cala** [comment] 2015-03-10 09:27
Partly fixed by https://github.com/classicdb/database/commit/de0ec204d86656d0343100af762c79296c7eb8c5 (needs core support for GO despawn). Quest is completable though.
