### ISSUE TITLE
Ammo for Rumbleshot Completed Quest Script Missing

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#522] opened 2014-08-03 02:32 UTC
This quest http://www.wowhead.com/quest=5541/ammo-for-rumbleshot has a completed quest script which is one of my favorites.  I don't know if this has been raised as yet but it's missing atm.  I pretty sure it could be handled by the DB script.  Doesn't appear to be anything too complicated.
The best video I could find of the event is https://www.youtube.com/watch?v=wCe_9PlTKsw
Such a great shame when it was taken out post-cataclysm and a big reason why I'm a supporter of projects such as this one

**Comment by cala** [comment] 2014-08-03 13:03
Thank you for this report. The issue is already open in #138 so I'm closing this one.

**Closed as completed by cala** 2014-08-03 13:03 UTC
