### ISSUE TITLE
Gnogaine

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#750] opened 2015-02-24 11:45 UTC
You should use the item at some NPCs. At the moment you can use it everywhere and you don't even need to have a target to complete the quest.

Quest: http://de.wowhead.com/quest=2926/gnogaine
Item: http://de.wowhead.com/item=9284
NPCs: http://de.wowhead.com/npc=6213/bestrahlter-eindringling http://de.wowhead.com/npc=6329

**Comment by Muehe** [comment] 2015-05-13 21:17
Tested. Could not reproduce as described.

Quest is working for me (with one exception). The empty phial says "Invalid Target" if used with no target or the wrong one. You can however collect with it, when targeting the right NPC and being close enough (if not it says "Invalid Target", should say out of range). So according to the quest log it works fine. [WoW-Head comments](http://de.wowhead.com/quest=2926/gnogaine#english-comments) suggest otherwise though:

> By contentious 2006.11.25 (Patch 1.12.2)
> In order to do this quest you need to have the flask ready, with either your bag open or on one of your action bars. When one of the caster Troggs begins to cast his spell(his hands will glow green) right click the flask. You'll collect the goo. He'll still shoot you though, so be ready to take him down after that.

Casting/Fighting status is irrelevant right now. Also:

> By Mordenthal 2007.02.27 (Patch 2.0.8)
> Actually the corpses that glow green can also be used to fill the phial. So just kill some troggs and use the phial on the corpse.

Corpses return "Invalid Target". Or to be more precise, there were no "corpses that glow green". Might have worked differently with Classic/TBC, but quest doesn't seem to work 100% as intended either way. Additional Source:

> You need to Use the Empty Leaded Collection Phial on one of the trogs that glows green (the Irradiated Invaders and Irradiated Pillagers). There are many of these outside the actual instance. You have to complete the collection before the creature dies. And it doesn't always succeed. If you fail, keep trying. 
> http://www.wowwiki.com/Quest:Gnogaine?oldid=717743 Revision as of 18:26, June 25, 2007

No failed tries in ~10 (deleting the filled phial, then using .additem). Failed tries, as described here, support the comment from contentious on WoW Head, that the target needs to be casting. Right now you need to target and be close.

**Comment by cala** [comment] 2015-05-16 21:42
Thanks @Muehe for this research.
From what I read in the the comment, one guy says it works on corpse, the next one says it does not work. Which one is right?

The missing green glow on corpse may also be related to a core issue that should be fixed soon.

Anyway, the quest works fine and the polish that could be brought to it (if relevant) requires core update. So, I'm closing here. Thank you.

**Closed as completed by cala** 2015-05-16 21:42 UTC
