### ISSUE TITLE
Tools for Steelgrill Quest

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#517] opened 2014-08-02 13:21 UTC
This quest (400) needs to have a gender option included in the OfferRewardText section.  Beldin is hardcoded to reply "Well done, lad,......." This should contain the gender modifer (lass or lad) to make the appropriate reply.

**Comment by cala** [comment] 2014-08-04 12:00
As strange as it may seem, this quest text only has "lad" and various sources confirmed this. Maybe an error from blizz or it was intended to give some personnality to the NPC.

Thank you for the report, I'm closing the issue.

**Closed as completed by cala** 2014-08-04 12:00 UTC
Labels: Quest, Gossip Menu, Enhancement
