### ISSUE TITLE
Mr. Smite

### ISSUE THREAD

**Issue by katz1** [classicdb/database#906] opened 2016-10-02 09:50 UTC
In deadmines when I reached the ship I found Mr. Smite waiting on the ship. He came down when I pulled the hiding rogues at the bottom of the ship's bridge. I believe Mr. Smite should wait at the bottom of the bridge between the two rogues, but I could be wrong. (Or he goes up to the ship if the party is entered the area by blasting the door?)

![wowscrnshot_100216_093436](https://cloud.githubusercontent.com/assets/18726138/19019869/3590f4ac-8896-11e6-9e40-b9413f97a884.jpg)

Mr. Smite has dialogue when he switches weapons during the fight. These were present in the chat but the voice was missing.

![wowscrnshot_100216_093614](https://cloud.githubusercontent.com/assets/18726138/19019871/5965a012-8896-11e6-99df-e4129af57ebf.jpg)

**Comment by Phatcat** [comment] 2016-10-02 15:07
https://www.youtube.com/watch?v=q6r431x9bPI 7:22 - smite is where he's supposed to be =)

**Comment by Phatcat** [comment] 2016-10-06 14:08
I see another problem with him, though, if you had him stunned (which it looks like in the picture) then he should not be able to use his stomp (look at the video)

**Comment by cala** [comment] 2016-10-09 20:21
Just tested right now and the voices are here. These are the sound IDs 5778 and 5779.
So everything is as intended, I'm closing this issue. Thank you.

**Closed as completed by cala** 2016-10-09 20:21 UTC
