### ISSUE TITLE
quest 648 "Rescue OOX-17/TN!"

### ISSUE THREAD

**Issue by RichardGe** [classicdb/database#821] opened 2016-03-13 11:34 UTC
Hi,

When I start the quest 648 "Rescue OOX-17/TN!",
the robot doesn't move.
However, the quest seems implemented inside  mangos/src/scriptdev2/scripts/kalimdor/tanaris.cpp
So I don't know what is happening.

item that starts the quest : 8623
position of the robot:   .go zonexy 60.2 64.6 440

**Comment by cala** [comment] 2016-03-14 08:03
Typical dev answer: "It works for me".

I tested right now and the NPC starts the escort quest. Could you check that SD2 is working, please?

**Comment by Lumber-Jack-2** [comment] 2016-03-14 11:00
maybe some player started the quest, then run away from the grid of the chicken
it could be the case that this behaviour create bugs for the ecortAI

**Comment by killerwife** [comment] 2016-03-17 08:18
Possible problem is that the chicken is supposed to be set as active object when the escort starts. Problem is current cmangos doesnt correctly support active creatures as im told. On retail the chicken would move/die even if the player left the chicken.

**Comment by cala** [comment] 2016-03-17 09:07
What you are referring to is a different issue, related to how the escort quests are handled in core. @RichardGe was saying that the quest escort does not even start and I can't reproduce that issue, hence my suggestion to check that SD2 is loaded/working.

**Comment by RichardGe** [comment] 2016-03-17 17:35
I'm currently investigating if SD2 is correctly installed. maybe it's not because SD2Error.log is saying "Configuration file version doesn't match expected version. Some config variables may be wrong or missing."

**Comment by RichardGe** [comment] 2016-03-17 17:44
ok, I have executed the line :
mysql -uroot -p mangos < mangos/sql/scriptdev2/scriptdev2.sql
and now the chicken seems to work :)

However, note that I still have the message "Configuration file version doesn't match expected version. Some config variables may be wrong or missing." in SD2Error.log
Is this expected ?

**Comment by RichardGe** [comment] 2016-03-17 19:35
The chicken is now moving. But quest has some issue on my server :
1) after the first 3 scorpions attack, the chicken will continue to move with the died animation (even if he has 100% of life, see my screenshot). This is just rendering.. so this doesn't prevent to finish the quest
2) The chicken doesn't aggro the random mobs directly. he only attacks them if the player has aggro them. I think this was not like that in the original wow ?
3) biggest issue preventing the finish of the quest, is that, sometimes, after attacking random mobs, the chicken will run fast backward for a while and disappear.

when I say "random mobs", I'm talking of the Tanaris mobs that the player&chicken will meet during the escort. Not the mobs spawned by the escort script.

![asup_wowchi](https://cloud.githubusercontent.com/assets/2279126/13858253/19cccb4c-ec7e-11e5-8419-1de74a0a9223.png)

**Comment by cala** [comment] 2016-03-18 08:44
> However, note that I still have the message "Configuration file version doesn't match expected version. Some config variables may be wrong or missing." in SD2Error.log
> Is this expected ?

It means that your configuration file for SD2 does not have the same version that the one expected by the core. I have the same issue since the integration of SD2 into core (which is expected for I did not update my SD2 conf file since). I don't know (yet) if the SD2 config file is still needed now. Whatever, this message is unrelated to your issue and can be ignored for now.

> after the first 3 scorpions attack, the chicken will continue to move with the died animation (even if he has 100% of life, see my screenshot). This is just rendering.. so this doesn't prevent to finish the quest

I'm surprised by this one. Can you explain how the chicken got the "dead" animation, please?

> The chicken doesn't aggro the random mobs directly. he only attacks them if the player has aggro them. I think this was not like that in the original wow ?

This is related to SD2 behaviour: when starting an escort quest, NPCs are assigned a temporary escort faction, by default this faction does not aggro random NPCs. There are other possibilies of escort factions, some aggroing nearby NPCs, like what I did in : https://github.com/scriptdev2/scriptdev2-classic/commit/a2257fbcee76c17d3cb8b175f50236a99f3d39ea

> biggest issue preventing the finish of the quest, is that, sometimes, after attacking random mobs, the chicken will run fast backward for a while and disappear.

When leaving combat, the escort NPC will move back to its previously reached waypoint which can be far behind if the path is very linear (or the developer lazy). When this happens, if the player does not catchup quick enough, the NPC can be removed from grid. Unless some systems are rewritten in core, I can only advice to:
- increase the various ranges in mangosd.conf 
- run faster :p

**Comment by RichardGe** [comment] 2016-03-19 16:11
Here is a video:
https://youtu.be/7hwbF2ZpgO4
01:10 - after the first attack, the chicken has the 'died' animation.
04:10 - chicken runs too far behind, and disappears (Maybe more waypoints should be added)
( Note that I kill NPCs with the .die command )

**Comment by cala** [comment] 2016-03-21 16:30
Thank you for this video. I'm really puzzled by the 'dead chicken' animation. There's something weird here.

I don't know if the waypoints in the SD2 script come from sniffs or were manually added, so it 's hard to tell if we should add more. However, it looks like the chicken is running far too quickly because the player can't even catch with it. I have to check the speed in DB.

**Comment by killerwife** [comment] 2016-03-21 17:10
Doesnt the chicken reset to creature_template entry when it "just returned home" ?

**Comment by RichardGe** [comment] 2016-04-09 11:00
The die animation is not specific to the chicken.
It's also present in the escort quest  3367 : "Suntara Stones" started by Dorius Stonetender. :
![asup_escort](https://cloud.githubusercontent.com/assets/2279126/14403328/d9c451b4-fe52-11e5-982e-dd1d61d3d46f.png)
(in this screenshot, Dorius is alive and "walking")

**Comment by killerwife** [comment] 2016-04-09 11:48
Does he have dynflag DEAD set? Afaik its 32 UNIT_DYNFLAG_DEAD

**Comment by killerwife** [comment] 2016-04-09 14:34
select \* from creature_template_addon where entry=8284; bytes1 is set to 7, which means he is lying on the floor dead

m_creature->SetByteValue(UNIT_FIELD_BYTES_1, 3, 0); needs to be done in code at start of escort afaik

EDIT: need to check when load addon is called, if its not at leaving combat or something similar

**Comment by cala** [comment] 2017-07-09 13:31
Poke @xfurry 

Long time without seeing you, I hope you are doing well and that everything is fine.

I can managed to get in touch with you on IRC. Please, can you explain here what you had in mind [in this comment](https://github.com/scriptdev2/scriptdev2-classic/commit/55dbc9abf5fecb708ce4fd44b75dbd29a7403514#commitcomment-17505665) so we can close this long due issue. Thanks !

**Comment by killerwife** [comment] 2017-07-09 13:35
As much as I dont want to butt in, creature_addon cant be used for this. Need to remove it from DB, and only set it at spawn in JustRespawned() of the AI.

**Comment by xfurry** [comment] 2017-07-09 17:50
@cala I am doing fine, thank you. I hope you are doing fine as well.
Sorry, for the low activity lately. I'm still struggling to setup my new desktop machine. Unfortunately I got some serious delays because of the [graphic card shortage](http://www.pcworld.com/article/3199257/components-graphics/why-amds-radeon-graphics-cards-are-almost-impossible-to-buy-right-now.html).

**Comment by cala** [comment] 2018-02-09 20:54
Part of this is fixed in https://github.com/cmangos/classic-db/commit/a863a9c5575cbc14ee1ff33ea0315574e63a75fa
There are still some issues with the quests that I intend to fix SD2-side later. Same treatment for the "Suntara Stones" will occur.

**Comment by cala** [comment] 2020-05-15 10:04
Now fixed and working nicely.

**Closed as completed by cala** 2020-05-15 10:04 UTC
Labels: Quest, Core / ScriptDev2
