### ISSUE TITLE
Dire Maul Fixes

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#113] opened 2013-09-04 17:11 UTC
Ironbark the Redeemed wasn't spawning after Zanzil's death.

The door after the final boss (Alzzin) wasn't opening after his death.

INSERT INTO `dbscripts_on_creature_death` (`id`, `delay`, `command`, `datalong`, `datalong2`, `buddy_entry`, `search_radius`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES 
(11492, 0, 11, 14813, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Open Crumble Wall after Alzzin\'s Death'),
(11490, 0, 18, 0, 0, 11491, 138118, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Despawn Old Ironbark after Zanzil\'s Death'),
(11490, 0, 10, 14241, 0, 0, 0, 0, 0, 0, 0, 0, -72.171898, -283.252014, -57.749699, 4.084070, 'Spawn ironbark the redeemed after Zanzils death');

**Comment by Schmoozerd** [comment] 2013-09-04 19:34
no, none of these fixes is proper i think.
See https://github.com/scriptdev2/scriptdev2/blob/master/scripts/kalimdor/dire_maul/instance_dire_maul.cpp

I cannot tell what is going on directly, but the door after alzzin is supported with sd2.

> case TYPE_ALZZIN:                                   // This Encounter is expected to be handled within Acid (reason handling at 50% hp)
> ..
> DoUseDoorOrButton(GO_CRUMBLE_WALL);

Maybe there is some mismatch with zanzil and zevrim?

> case TYPE_ZEVRIM:
> ...
> pIronbark->UpdateEntry(NPC_IRONBARK_REDEEMED);

**Comment by cala** [comment] 2013-09-05 09:25
I was thinking the same. Maybe something in the database is wrong/missing and prevent SD2 from working as intended?
Now that version 1.2.0 is released, I will have a better look on DM and UBRS/LBRS that had many reports lately.

**Comment by scotty0100** [comment] 2013-09-07 18:02
Apologies, I should have looked in further into SD2. However, on the topic of dire maul fixes then, I'll add them to here if I see anything that doesn't look right. I'm looking at old dire maul instance run videos and comparing them to cMangos core.

First one I noticed so far is Guard Fengus at the moment stands over the box; however on retail he seems to wonder around the platform and then seems to charge the center if the box gets looted.

Source 1: https://www.youtube.com/watch?feature=player_detailpage&v=KVyqLWOWPZ0#t=356
Source 2: https://www.youtube.com/watch?feature=player_detailpage&v=iSumJg7dm1c#t=140
Source 3: https://www.youtube.com/watch?feature=player_detailpage&v=aOb8qB8G4x4#t=348

On source 2 it looks like he is avoidable also. So maybe can have him charge to the location rather than to the player.

Will continue to add dire maul issues here if that's OK :+1: 

EDIT: I don't think he charges when the box is looted actually, looking at source 2 again he is just walking slowly, it's just because the video is sped up it looks faster, I think he just paths across there as well.

**Comment by scotty0100** [comment] 2013-09-11 20:09
Lethtendris & Pimgib pathing around the campfire. Source: http://www.youtube.com/watch?feature=player_detailpage&v=hdU-IWdLZ54#t=131

Currently they stand still.

**Comment by scotty0100** [comment] 2013-09-11 20:20
Fairly big bug in Dire Maul also; after killing King Gordok and speaking to Mizzle the Crafty, you can spawn an unlimited amount of chests by keep going back and talking to him.

Would you rather me separate these bugs in new issues or this OK?

**Comment by scotty0100** [comment] 2013-09-11 21:26
Knot Thimblejack's Cache is currently located underneath Immolthar. I believe it should spawn next to Knot after you complete the "Free Knot" quest.

**Comment by cala** [comment] 2013-09-12 11:46
Thank you for all these reports. I prefer you open separate issues, it is easier to keep track of it.
There is also a big report already opened about Dire Maul: https://github.com/classicdb/database/issues/77

I tested yesterday the first ones: I confirm Ironbark/Zevrim/Alzzin events work as intented with SD2. The only errors I noticed were Alzzin using only partially its ACID script (to be checked further).

Many creature movements/patrols are missing in DM, flags are not OK or positions wrong. I'm slowly working on everyone of these. Thank you. :+1:

**Comment by cala** [comment] 2013-10-27 13:47
> Lethtendris & Pimgib pathing around the campfire. Currently they stand still.

Is fixed by https://github.com/classicdb/database/commit/3871dacce4c9ff7e2c2f8e3ef29d553452005872

**Comment by cala** [comment] 2015-01-02 16:34
> First one I noticed so far is Guard Fengus at the moment stands over the box; however on retail he seems to wonder around the platform and then seems to charge the center if the box gets looted.

Fixed in https://github.com/classicdb/database/commit/9dfad04c5c4671ca76e655bb1d92cd7f72c1680a

**Comment by cala** [comment] 2015-03-25 15:52
Mizzle and Gordok's cache are fixed by https://github.com/classicdb/database/commit/94a05ca598dc32a62d531aa43f4ae831511afda4

**Comment by cala** [comment] 2015-04-27 15:38
All sub issues described in this thread are now fixed. Thanks everyone.

**Closed as completed** 2015-04-27 15:37 UTC
Labels: NPC, Non-functional, Game Object, Dungeon
