### ISSUE TITLE
[Blackrock Depths] The Grim Guzzler - Mistress Nagmara

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#415] opened 2014-05-01 13:04 UTC
After completing the quest 'The love potion', [Mistress Nagmara](http://www.wowhead.com/npc=9500), located in the Grim Guzzler, should give a gossip-option to start a little event to open the doors for you to progress further without fighting the Phalanx.

**Comment by cala** [comment] 2014-05-06 09:11
Thanks. As mentioned elsewhere I did not take a single run in BRD since I started Classic DB, so there are probably more of these. :)

Adding the gossip menu is pretty straightforward. Part of the event is already scripted in SD2, I have to check what is missing first.
https://github.com/scriptdev2/scriptdev2-classic/blob/master/scripts/eastern_kingdoms/blackrock_depths/blackrock_depths.cpp#L541

**Comment by evil-at-wow** [comment] 2014-05-09 22:50
Looking at that SD2 link, everything seems missing. The Private Rocknot part that is implemented there is the part where he, after giving him six ale total, starts wandering around the bar attacking barrels. Then he breaks one barrel, which opens the door to be able to continue (though Phalanx hops out of his corner, barring the door and turning aggressive).

**Comment by cala** [comment] 2015-07-08 08:10
I'm starting to look at the Grim Guzzler which is indeed in a grim state (pun intended) and I don't dare to imagine how dire it was before the fixes Tobschinski already made to it !
Anyway, I think this quest is to be handled by SD2 and for that if you have some data describing how it should work (waypoints, spells, timers...), it would be very nice, please, as I did not manage to find a single video of it and last time I did this quest was VERY long ago. :(

**Comment by Tobschinski** [comment] 2015-07-08 12:26
I did this, I just need to find it, I never published it because there was something not working, but I cannot remember ...

**Comment by cala** [comment] 2015-07-23 20:17
As said, I started the rework of all the Grim Guzzler events. Almost all of it will be done with SD2: https://github.com/scriptdev2/scriptdev2/pull/175/

Since the scripts will compete over interacting with three objects there (Rocknot, Phalanx and the bar door), I would like to have confirmation/feedback on the various possibilities described below, please. 

**Nagmara and the Potion of Love**
Since this is a quest, I assume that whatever has already happen in the Grim Guzzler, the event should happen. Also, there's nothing that could prevent it since Rocknot and Nagmara never go hostile to anything.

**Plugger Sparring**
I also think that Plugger could be pickpocketd/engaged even if the door was already open in any other way.

**Rocknot**
Will Rocknot attack the barrels if the door is already open (either by the players after killing Plugger or by the guards after killing a patron)? I would say: yes.
I assume that Rocknot will not attack the barrels if Nagmara already came to him: he'll probably have better things to milk from...

**Guards spawn**
A firelord and 3 guardsmen will open and come through the back door the first time a _neutral_ patron is killed.
Will this happen if the door was already open in another way? I would say: no.

**Phalanx**
Phalanx will turn hostile (faction is to be confirmed) to any player if Rocknot breaks the barrel and it will move to guard the door.
[Comments on wowhead](http://www.wowhead.com/npc=9502/phalanx#comments) say this is temporary and that it should reset after some time, returning to its original faction and spawn point. Timer is unknown, if this is true.
Phalanx will turn to faction Ironforge if Plugger is engaged and also move to guard the door.
[Comments on wowhead](http://www.wowhead.com/npc=9502/phalanx#comments) say this is temporary and that it should reset after some time, returning to its original faction and spawn point. Timer is unknown, if this is true.

If you can bring some light to these, I'll be very happy. :+1:

**Comment by Tobschinski** [comment] 2015-07-24 10:03
> **Nagmara and the Potion of Love** 
> Since this is a quest, I assume that whatever has already happen in the Grim Guzzler, the event should happen. Also, there's nothing that could prevent it since Rocknot and Nagmara never go hostile to anything.

Nagmara and Rocknot will always teleport out of the bar after any hostile action was performed.

> **Plugger Sparring**
> I also think that Plugger could be pickpocketd/engaged even if the door was already open in any other way.

Yes.

> **Rocknot**
> Will Rocknot attack the barrels if the door is already open (either by the players after killing Plugger or by the guards after killing a patron)? I would say: yes.
> I assume that Rocknot will not attack the barrels if Nagmara already came to him: he'll probably have better things to milk from...

He is no longer present if that has happened. He is also untargetable if you speak with him or Nagmara.

> **Guards spawn**
> A firelord and 3 guardsmen will open and come through the back door the first time a neutral patron is killed.
> Will this happen if the door was already open in another way? I would say: no.

Yes, that should always happen if you kill Spazzring or a Patron (with a short delay) I'll check that.

> **Phalanx**
> Phalanx will turn hostile (faction is to be confirmed) to any player if Rocknot breaks the barrel and it will move to guard the door.
> Comments on wowhead say this is temporary and that it should reset after some time, returning to its original faction and spawn point. Timer is unknown, if this is true.
> Phalanx will turn to faction Ironforge if Plugger is engaged and also move to guard the door.
> Comments on wowhead say this is temporary and that it should reset after some time, returning to its original faction and spawn point. Timer is unknown, if this is true.

Faction is 54 if you ask Rocknot to open the door.
If you kill Spazzring, the faction should be 122. The faction is changed whenever he starts guarding the door (last waypoint).
A message is displaed if he starts his path: Violence!  Property damage!  None shall pass!!

I have no idea if this is temporary, will check.

**Comment by evil-at-wow** [comment] 2015-07-25 17:09
I can only confirm the last part of Rocknot with 100% certainty. Once you complete the love potion quest, Nagmara and Rocknot will run out of the bar - opening the door if needed - and and be unavailable for further quests/gossip. 

As far as I know - but I have never camped them for hours - they will stay ingame where they make love for the rest of the instance, so I believe Tobschinski means 'no longer present in the bar' when he says 'no longer present'. I'm sure he'll correct me if they do despawn after all.

**Comment by Tobschinski** [comment] 2015-07-26 16:26
If you attack the dwarfs or Plugger Spazzring, both, Nagmara and Rocknot, will say something and cast a spell to fake a teleport out of the dungeon They will not return.

**Comment by evil-at-wow** [comment] 2015-07-27 18:08
Oh, I see what you mean now! I was kind of confused by the following when it flew through my brains:

> I assume that Rocknot will not attack the barrels if Nagmara already came to him
> 
> > He is no longer present if that has happened

But it turns out your first sentence applied to cala's first sentence instead of the one I quoted. The one which was talking about wreaking havoc with the bar.  But crisis averted.

**Comment by cala** [comment] 2015-07-28 14:15
Thanks both of you for your feedback. :+1: 

 I found three videos that sheds more light on how the things are expected to be:
- One video from Classic days: https://www.youtube.com/watch?v=HQpoksHqVig
- One video from WotLK days: https://www.youtube.com/watch?v=3mIkmIdpEW4
- One video from Cata days: https://www.youtube.com/watch?v=GR_CQ-eC6ns

From those, I came to the following conclusions:
- Private Rocknot will despawn, saying "I'm out of here." only when patrons turns hostile
- Patrons turn hostile when Plugger is killed (not when he's engaged, nearby patrons just assist him without changing faction)
- The cata video lets think that patrons do not turn hostile when one of them is killed, but from my memory and from what the WoW dungeon companion says, they should turn all hostile as soon as one of them is killed. Thus, I assumed this was changed in Cata
- The Classic videos makes me think that patrons that are lured away by Dark Iron Ale can be killed safely without turning all the others hostile (unless the cata video is right)
- If my memory serves, stealing from one of the beer/boar GOs has a chance to make Plugger hostile and turns everyone hostile

**Comment by cala** [comment] 2015-08-27 15:38
More details from http://www.wowhead.com/npc=9499/plugger-spazzring#comments and some old videos:
- stealing beer/boar GOs makes Plugger warn the players the two first times and turns hostile (along with the whole bar) on the third time
- it seems that killing one of the patron does not turn the bar hostile nor spawn the patrol, this is confirmed by many videos from rogues/druid soloing Plugger after pulling the nearby patrons one by one without turning the bar hostile (including videos from Classic days: https://www.youtube.com/watch?v=fYPFwKB_68k or https://www.youtube.com/watch?v=1gMZRxSYNiE )
- the patrol is spawned when killing Ribbly or Plugger instead. This seems to be consistent with the Cata video above and this video https://www.youtube.com/watch?v=1gMZRxSYNiE .

There's only one conflicting information here: does killing a neutral patron turn the whole bar hostile?
Many sources say "no" (comments and videos) and one says yes (BRD walkthrough in WoW Dungeon Companion from 2006). I trust the Companion on many things, but it also has proven to have outdated data (we are aiming 1.12.1 content here) and it does not cover things from late patches (Naxxramas is missing). I think that here, the Companion is wrong (or at least outdated). Sorry, dear companion.

So unless you disagree (and I'm ok to discuss this):
- I will only spawn the patrol if Ribbly or Plugger are killed
- The patrons will turn hostile only if Plugger makes them so (pickpocketed, beer stolen, killed)

I will push a commit handling the patrol to the currently open PR in SD2 this evening or tomorrow evening https://github.com/scriptdev2/scriptdev2/pull/175
It will only cover the Ribbly part first, the Plugger will wait the commit dedicated to Plugger that will follow shortly. :smile:

**Comment by Tobschinski** [comment] 2015-08-27 17:20
The patrons will only turn hostile if you kill Plugger Spazzring (I will  look again to see what happens if he resets). 
Stealing the goods (3 of them in total) will not directly affect any patrons around, just Plugger will turn hostile.

**Comment by cala** [comment] 2015-08-28 07:12
Thanks for this precision. I will then only trigger the patrons hostility on Plugger's death, though I don't know why people would get angry on some gnome's death instead of rejoicing and cheering...

**Comment by Tobschinski** [comment] 2015-08-28 09:45
Because he is the only person around that sells beer.

**Comment by evil-at-wow** [comment] 2015-08-28 19:27
I don't have memories that say something else, nor do I currently have data that suggests otherwise, so for what it's worth: you have my vote and support to go with your final conclusions, @cala.

**Comment by cala** [comment] 2015-08-29 12:58
I updated the PR with a commit handling the patrol: https://github.com/cala/scriptdev2/commit/902fd0a8bfc73a74416491856de3641d72f73186 . It also contains basic work for Plugger (like an option to turn the whole bar hostile)

What remains to be done in the Grim Guzzler are : 
- everything related to Plugger (I'm on it)
- Mistress Nagmara and the Potion of love event

Tobschinski told me he already nailed down Nagmara (pun intended), so if you want to push it to the current pull request, you are free to do it, or I can adapt it myself if you prefer. That's up to you!

Whatever, I took care of adding the despawn of Rocknot and Nagmara in the previous commit to avoid any conflict.

**Comment by Schmoozerd** [comment] 2015-08-29 17:49
Gnomes are inmortal (too small to get noticed by death himself)

**Comment by cala** [comment] 2015-09-04 11:51
I've nearly finished the Plugger script and I shall test it this week-end.
Unless Tobschinski wants to do it, Nagmara and the Potion of Love are next on my list. However, I have zero retail data on the matter, so if you have something that you could provide to me, that would be much welcome.

Still regarding Nagmara, she does some requests/answers says with the patrons while wandering. I have all texts I think, but I don't know if they are triggered by waypoint or by NPCs (patron) distance check or are completely random. I would say the first, but I'm not sure.

**Comment by Tobschinski** [comment] 2015-09-04 12:04
You know the dark place where you always get your drugs, so come and meet me there.

**Comment by cala** [comment] 2015-10-14 07:22
I scripted the event in https://github.com/cala/scriptdev2/commit/f3b7bbe54cd0d6dba81b22b83eb659333598f252
All BRD related parts requiring SD2 are now scripted in this [pull request](https://github.com/scriptdev2/scriptdev2/pull/175) pending review and backport. So I'm closing this issue on the DB side.

**Closed as completed by cala** 2015-10-14 07:22 UTC
Labels: NPC, Non-functional, Game Object, Core / ScriptDev2, Dungeon
