### ISSUE TITLE
Jandice Barov

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#716] opened 2015-01-21 18:57 UTC
When the NPCs summons its illusions you should loose your target so that you have to find her. At the moment she is still your target.

NPC: http://www.wowhead.com/npc=10503

Sources:
https://web.archive.org/web/20070817110742/http://wow.allakhazam.com/db/mob.html?wmob=11439
http://wowpedia.org/Jandice_Barov_%28original%29
http://wowdata.buffed.de/npc/Jandice-Barov-10503#comments (german)

**Comment by cala** [comment] 2015-12-11 16:11
Poke @evil-at-wow : by any chance, do you have sniffed data of Scholomance? I have a few things I'd like to confirm for this dungeon, please. :)

**Comment by Tobschinski** [comment] 2015-12-11 18:42
or both razorfen dungeons, zg & lbrs ... I need a lot more. :)

**Comment by evil-at-wow** [comment] 2015-12-11 21:23
@cala I have some for Scholomance, but sadly not a lot. I think I have one full clear or so. 

@Tobschinski I have a few Razorfen Kraul runs, not sure about Razorfen Downs (I should have data from MoP 5.4.1 or 5.4.7 though, before they revamped it). Quite some LBRS data too, including the seal quest chain. 

Mind you: it's not Classic data, but data from early WoTLK (3.0.3, 3.0.8 etc). If you're interested, just ask what you wanted to know, and I'll see what I can find! 

Final note for Tobschinski: consider that Isalien request on the list now. I went to DM East and summoned her, so I should have the raw data. But with the new 6.2.3 patch all opcodes and structs are changed again, so I still have to parse the data.

**Comment by cala** [comment] 2015-12-14 13:59
_Only_ one full clear is always infinitely more than none at all. :)

If you have them, I'd like the following data, please. Since there are many of them, I separated them: the first list is the one I'd really like to have. The second one is optional (cosmetic changes, mostly)

High priority (there seem to be pull issues in the two top cases)
- spawn points of Lord Alexei Barov (ID 10504) and his two adds (should have ID 10489)
- spawn point and movement of the NPCs in the room below the brigde at the entrance (expected IDs: 10495 (Diseased Ghoul), 10481 (Reanimated Corpse), 10485 (Risen Aberration) and ID 11551 (Necrofiend)). They should be amongst the first NPCs to be loaded and expect a good twenty of them at least 
- data (template if possible) about the Illusion of Jandice Barov (ID 11439)
- flags and spells cast by Risen Aberration (ID 10485): I'm looking at the way they are granted immunity to all magic schools but holy

Low priority:
- spawn point of the Ravenian (ID 10507)
- spawn points of the few Risen Protector (10487)
- Movement and text of NPCs Melia (ID 11282) and Sammy (ID 11283): they are outside the instance, so chances are good that you may not have them due to the Dungeon Finder... But this would not be an issue since these NPCs are still in-game, the only trouble is they are invisible unless the player has finish the original Scholomance quest-line. Their movements and texts should nonetheless be sent to the client for players have reported "hearing" them even when they are invisible

I know you are vey busy, so take your time, there is no hurry here: Scholomance is in a better state than most dungeons in Classic and probably completable for more than 90% of the reasons one would want to run Scholomance.

**Comment by evil-at-wow** [comment] 2015-12-20 15:49
@cala I agree that some data is still better than no data at all. Allow me to dump the data for some low hanging fruit here. All data is from patch 3.0.3 build 9183.

The spawn points of Lord Alexei Barov and his adds. All three are static, no movement has been observed.

| entry | x | y | z | o |
| --- | --- | --- | --- | --- |
| 10504 | 178.724 | -91.0232 | 70.8568 | 1.64061 |
| 10489 | 175.266 | -88.1815 | 70.8568 | 1.5708 |
| 10489 | 183.088 | -88.0234 | 70.8568 | 1.53589 |

The spawn point of The Ravenian. Again static, no movement has been observed.

| entry | x | y | z | o |
| --- | --- | --- | --- | --- |
| 10507 | 103.305 | -1.67752 | 75.2183 | 6.17847 |

The spawn points of Risen Protectors.

| entry | x | y | z | o |
| --- | --- | --- | --- | --- |
| 10487 | 259.834 | 164.623 | 109.848 | 4.81711 |
| 10487 | 173.16 | 127.189 | 109.709 | 0.680678 |

These two are static, no movement has been observed. There are two more of these, that patrol around. Their waypoints are below. The point observed in the first SMSG_UPDATE_OBJECT packet does not exactly match one of these points though - which is fairly common with patrols - so it is hard to tell where exactly they spawn. But seeing the initial points were pretty close to one of the 'end points', I've put the waypoints in the order that they are most likely using (the first point being the spawn point).

| point | x | y | z |
| --- | --- | --- | --- |
| 1 | 198.753 | 172.576 | 109.796 |
| 2 | 199.584 | 131.6 | 109.794 |

| point | x | y | z |
| --- | --- | --- | --- |
| 1 | 175.819 | 152.749 | 109.474 |
| 2 | 206.841 | 152.003 | 109.795 |
| 3 | 251.372 | 152.721 | 109.731 |
| 4 | 206.841 | 152.003 | 109.795 |

I'll go sort out the spawns for that lovely room next, and then I'll see what else I can find.

**Comment by cala** [comment] 2015-12-20 23:02
Thank you very much @evil-at-wow !!!

 Good news: all the spawn points in current Classic DB are the same you posted here. :)
Bad news, the second static Risen Protector is correctly spawned but there is also a group of 4 NPCs nearby that can't be pulled without aggroing the protector too and I'm sure this is not right. My guess is that this group and the protector should be two separate entries in a pool. So, if this is possible, could you post the spawn points (and IDs) of the NPCs near the Risen Protector (let's say 20 yards max):

| entry | x | y | z | o |
| --- | --- | --- | --- | --- |
| 10487 | 173.16 | 127.189 | 109.709 | 0.680678 |

Please? Again, no hurry here. :)

**Comment by Tobschinski** [comment] 2015-12-21 05:54
HURRY UP MAN, it's been 7 hours already.

**Comment by evil-at-wow** [comment] 2015-12-21 18:45
Great news, everyone! The ~~slime~~ data is flowing again!

It seems my curiosity finally pays off. Apparently I also had a sneak peek in the instance after finishing the quest chain for the Skeleton Key. So I found some more old Scholomance data!
After analyzing the three sets of Scholomance data I now have, I came to the following results and conclusions for that lovely room under the bridge. All data below is from patch 3.0.3 build 9183.
- That room has exactly 33 spawns in all three sets.
- Exactly one of the spawns is a patrolling Necrofiend (11551).
- The remaining 32 spawns are divided as 8 groups with 4 spawns each (I'll save you the details of how I figured that out).
  - The 32 spawns have fixed spawn coordinates that match exactly between the sets.
  - The orientation of the spawns however, differs between the sets, for all points. This seems to be random (and kind of makes sense if you take into account the next point).
  - The 32 spawns are all using _random_ movement.
  - Each of these groups has exactly 2 Risen Aberration (10485), but they do not spawn in fixed positions in the groups. I've observed groups that, over the three sets of data, have Risen Aberrations in each possible position, so my conclusion is that any two points of a group can spawn a Risen Aberration.
  - The remaining two spawn points in a group were either a Diseased Ghoul (10495) or a Reanimated Corpse (10481). It looks like there is always at least one Diseased Ghoul though, because I have not seen two Reanimated Corpse spawns in 24 groups.
  - I assume that it was the intention that each of these 8 groups could be pulled separately (when done carefully enough, of course).

As far as three sets of data and 24 groups can be statistically significant, this translates into the following recipe to spawn such a group:
- Choose two points at random and spawn a Risen Aberration in each one.
- From the remaining two spawn points, pick one at random and spawn a Diseased Ghoul.
- In the remaining point, spawn a Diseased Ghoul or a Reanimated Corpse with 50/50 chance (in my data, the 24 groups have a ratio 11/13, so I'm guessing it's 50/50).

I don't think we can implement the above requirements with the current core functionality (if you remember my Dire Maul East respawn, I made a similar comment for the three trash groups before Alzzin the Wildshaper, which has similar pooling requirements). We can select two points out of four at random with pooling, but I don't think we can combine this with filling up the remaining ones. I suggest that for the time being we forget about the two random locations for Risen Aberrations and spawn two in a fixed location...

And finally, the data itself.

The 32 spawn points for the 8 groups. Remember, the orientation looks random, so I did not see a point to list one of them. You might as well use 0.

| X | Y | Z |
| --- | --- | --- |
| 187.034 | 86.5012 | 104.798 |
| 195.23 | 85.8773 | 104.327 |
| 191.688 | 90.8574 | 104.327 |
| 191.343 | 83.4603 | 104.327 |
| <br> | <br> | <br> |
| 217.701 | 86.1711 | 104.798 |
| 206.582 | 85.9061 | 104.327 |
| 211.313 | 88.8732 | 104.327 |
| 211.762 | 82.7032 | 104.327 |
| <br> | <br> | <br> |
| 179.126 | 94.6681 | 104.8 |
| 187.086 | 92.537 | 104.767 |
| 182.377 | 97.8408 | 104.799 |
| 180.356 | 102.901 | 104.798 |
| <br> | <br> | <br> |
| 179.885 | 73.8904 | 104.799 |
| 185.796 | 74.2217 | 104.799 |
| 185.034 | 80.1398 | 104.799 |
| 179.384 | 83.667 | 104.8 |
| <br> | <br> | <br> |
| 221.956 | 103.89 | 104.798 |
| 217.536 | 99.4131 | 104.798 |
| 221.917 | 96.4046 | 104.798 |
| 215.996 | 91.7486 | 104.798 |
| <br> | <br> | <br> |
| 196.721 | 91.9017 | 104.327 |
| 197.118 | 98.0816 | 104.798 |
| 204.37 | 92.5006 | 104.327 |
| 203.038 | 98.6992 | 104.798 |
| <br> | <br> | <br> |
| 215.633 | 79.811 | 104.798 |
| 214.38 | 73.1017 | 104.798 |
| 220.372 | 73.5207 | 104.798 |
| 222.002 | 82.2615 | 104.798 |
| <br> | <br> | <br> |
| 204.191 | 73.0652 | 104.798 |
| 198.144 | 73.889 | 104.666 |
| 197.559 | 79.5891 | 104.327 |
| 203.869 | 80.8282 | 104.327 |

Waypoints for the patrolling Necrofiend.

| Point | X | Y | Z |
| --- | --- | --- | --- |
| 1 | 206.346 | 80.7189 | 104.244 |
| 2 | 221.189 | 86.5182 | 104.715 |
| 3 | 207.384 | 91.5904 | 104.244 |
| 4 | 199.815 | 104.765 | 104.715 |
| 5 | 192.953 | 90.7216 | 104.244 |
| 6 | 178.803 | 86.621 | 104.716 |
| 7 | 192.998 | 81.0231 | 104.244 |
| 8 | 199.444 | 69.7478 | 104.716 |

I'm not sure this is 100% perfection. I found it interesting that my sets of data show the Necrofiend spawning at (x, y, z) = (209.233, 73.2819, 104.798) with a random orientation, and then moving to (x, y, z) = (199.659, 69.7415, 104.716) before repeating the list of waypoints above. I have not checked yet whether that spawning point and the "one off" waypoint is actually on the path determined by the repeating waypoints.

And finally, to be completely accurate, there are three Rat (4075) spawns in that room that are using _random_ movement too. The orientation seems, again, completely random.

| X | Y | Z |
| --- | --- | --- |
| 216.771 | 75.3716 | 104.798 |
| 210.642 | 99.2762 | 104.798 |
| 182.771 | 69.4884 | 104.798 |

Now shush @Tobschinski! You have new data to process, with more on the way!

**Comment by evil-at-wow** [comment] 2015-12-21 21:16
@cala I have good news and more bad news.

The good news is that the group near the Risen Protector you mention does exist. They are indeed quite close to the Risen Protector, and I'm not surprised to hear you can not pull the group without getting aggro from the Risen Protector. I've observed a group of four static spawns there in all three sets of data, in addition to the Risen Protector, so I'm afraid they are there.

Data set 1

| X | Y | Z | O | NPC |
| --- | --- | --- | --- | --- |
| 173.16 | 127.189 | 109.709 | 0.680678 | Risen Protector (10487) |
| 170.96 | 132.657 | 109.667 | 0.733038 | Spectral Tutor (10498) |
| 175.234 | 136.705 | 109.637 | 3.92699 | Scholomance Adept (10469) |
| 175.721 | 133.102 | 109.664 | 2.58309 | Scholomance Adept (10469) |
| 171.38 | 136.536 | 109.638 | 5.49779 | Scholomance Necromancer (10477) |

Data set 2

| X | Y | Z | O | NPC |
| --- | --- | --- | --- | --- |
| 173.16 | 127.189 | 109.709 | 0.680678 | Risen Protector (10487) |
| 170.96 | 132.657 | 109.667 | 0.733038 | Spectral Tutor (10498) |
| 175.234 | 136.705 | 109.637 | 3.92699 | Scholomance Adept (10469) |
| 175.721 | 133.102 | 109.664 | 2.58309 | Scholomance Necromancer (10477) |
| 171.38 | 136.536 | 109.638 | 5.49779 | Scholomance Necromancer (10477) |

Data set 3

| X | Y | Z | O | NPC |
| --- | --- | --- | --- | --- |
| 173.16 | 127.189 | 109.709 | 0.680678 | Risen Protector (10487) |
| 170.96 | 132.657 | 109.667 | 0.733038 | Spectral Tutor (10498) |
| 175.234 | 136.705 | 109.637 | 3.92699 | Scholomance Necromancer (10477) |
| 175.721 | 133.102 | 109.664 | 2.58309 | Scholomance Adept (10469) |
| 171.38 | 136.536 | 109.638 | 5.49779 | Scholomance Necromancer (10477) |

Which brings me to the more bad news. The fact that you can not aggro the group without getting aggro from the Risen Protector, means there is something wrong in how the core handles aggro. I have to say that I've had that feeling on numerous occasions before, where I pull something on my TBC server and aggro more than I anticipated. 

If you'd ask me to come up with a root cause and reason, I would guess that the range for "transferring aggro to nearby NPCs" is simply too large in the core. This is most likely so since ages and was probably done in the core on purpose, to make sure you pull entire groups instead of peeling off single NPCs.

I guess we could reduce that range a bit and use creature linking to make sure entire groups aggro together where needed, although I'm not sure that's the best solution here because that's potentially a lot of additional creature linking! We need an improved spawning system that handles groups with less effort from the DB side...

**Comment by cala** [comment] 2015-12-22 12:53
> Great news, everyone! The ~~slime~~ data is flowing again!

You made my day with that one! :laughing: 

Thanks alot for these data. The room is much better.

Regarding the aggro, I was also afraid it would be something like this... Fortunately, the aggro range can be changed in mangosd.conf. However, I agree that a group system in core would be useful, but there is already many things to do/fix first.

**Comment by evil-at-wow** [comment] 2015-12-22 21:48
Ding! Let's answer the remaining questions.

First, the Illusion of Jandice Barov. My 'full clear' did not include any data for them, so apparently we skipped Jandice Barov in that run. I managed to find another set of Scholomance related data though, so do not despair! This data comes from patch 3.3.5a, build 12340.

The SMSG_UPDATE_OBJECT packet that spawns them has the following data.

```
  Position (x y z o) = (268.209 73.0848 95.9242 4.26356)
  Update field 0 = 0x0c33b3af
  Update field 1 = 0x2c0030f1
  Update field 2 = 0x09000000 [Type = 9]
  Update field 3 = 0xaf2c0000 [Entry = 11439]
  Update field 4 = 0x0000803f [Scale = 1.0]
  Update field 16 = 0xada8b107 [Created By 0 - Jandice Barov]
  Update field 17 = 0x290030f1 [Created By 1 - Jandice Barov]
  Update field 18 = 0x00000000
  Update field 19 = 0x00000000
  Update field 23 = 0x00010101 [UNIT_FIELD_BYTES_0]
  Update field 24 = 0x480c0000 [Health = 3144]
  Update field 27 = 0x64000000 [Power3 = 100]
  Update field 28 = 0x64000000 [Power4 = 100]
  Update field 29 = 0x40420f00 [Power5 = 1000000]
  Update field 32 = 0x480c0000 [Max Health = 3144]
  Update field 35 = 0x64000000 [Max Power3 = 100]
  Update field 36 = 0x64000000 [Max Power4 = 100]
  Update field 37 = 0x40420f00 [Max Power5 = 1000000]
  Update field 54 = 0x3d000000 [Level = 61]
  Update field 55 = 0xe9000000 [FactionTemplate = 233]
  Update field 56 = 0x0d330000
  Update field 59 = 0x00884800 [UNIT_FIELD_FLAGS]
  Update field 60 = 0x00080000 [UNIT_FIELD_FLAGS_2]
  Update field 62 = 0xd0070000 [Base Attack Time1 = 2000]
  Update field 63 = 0xd0070000 [Base Attack Time2 = 2000]
  Update field 65 = 0xb81e853e
  Update field 66 = 0x0000f03f
  Update field 67 = 0x412b0000 [Display ID = 11073]
  Update field 68 = 0x412b0000 [Native Display ID = 11073]
  Update field 80 = 0x0000803f
  Update field 81 = 0x6d450000 [Created By Spell 17773]
  Update field 122 = 0x01000000 [UNIT_FIELD_BYTES_2]
  Update field 146 = 0x0000803f
```

It is worth mentioning that she summoned 15 of these Illusions, all on the exact same coordinates and with the same orientation. The fields are interpreted as in the WoTLK core, so they should be reliable. To help with filling the creature_template, I've also dumped another packet (offset in hex - raw data as hex bytes - ASCII text).

```
SMSG_CREATURE_QUERY_RESPONSE

00000000: af2c 0000 496c 6c75 7369 6f6e 206f 6620   .,..Illusion of 
00000010: 4a61 6e64 6963 6520 4261 726f 7600 0000   Jandice Barov...
00000020: 0000 0000 0000 0006 0000 0000 0000 0001   ................
00000030: 0000 0000 0000 0000 0000 0041 2b00 0000   ...........A+...
00000040: 0000 0000 0000 0000 0000 0000 0080 3f00   ..............?.
00000050: 0080 3f00 0000 0000 0000 0000 0000 0000   ..?.............
00000060: 0000 0000 0000 0000 0000 0000 0000 0000   ................
```

And interpreted as the WoTLK core does, this results in:

```
Entry = 0xAF2C0000 = 11439
Name = 'Illusion of Jandice Barov'
Name2 = ''
Name3 = ''
Name4 = ''
Subname = ''
IconName = ''
CreatureTypeFlags = 0
CreatureType = 6
Family = 0
Rank = 1
KillCredit = [0 0]
ModelID 1 = 0x412B0000 = 11073
ModelID 2 = 0
ModelID 3 = 0
ModelID 4 = 0
Health Multiplier = 0x0000803F = 1.0
Power Multiplier = 0x0000803F = 1.0
Racial Leader = 0
QuestItems = [0 0 0 0 0 0]
MovementTemplateID = 0
```

Second on the list: Risen Aberration immunity to all magic schools except holy. So far, I've not been able to find anything interesting. The SMSG_UPDATE_OBJECT packet that spawns them does not include any relevent info as far as I know. After spawning, an SMSG_AURA_UPDATE_ALL is sent with no auras. The only aura update I've found is one related to spell 12021 (Fixate). I've also found them casting two spells on themselves: spell 12021 (Fixate) and spell 1604 (Dazed). I don't know why they cast Dazed though. So unless I haven't found the interesting data yet, it looks like they are "naturally" immune, similar to how most elementals were/are immune to their own school. Something along the line of MechanicImmuneMask, say, but for schools of magic instead of mechanics.

Finally, Melia and Sammy. It turns out that data for them is **not** sent to the client when you can't see them! None of the ghosts of Caer Darrow were spawned, and their movement didn't reach my client either. I only seem to get the SMSG_MESSAGECHAT packet with their text. There is also good news: the set of data for Jandice Barov above also has me complete the quest to get a Spectral Essence! So here is some more data from patch 3.3.5a, build 12340.

All texts below are type 12 (CHAT_MSG_MONSTER_SAY) and language 0 (LANG_UNIVERSAL). The SMSG_MESSAGECHAT packets and my interpretation follows.

```
0000:0000|0c 00 00 00 00 c9 0d 00 12 2c 00 30 f1 00 00 00|.........,.0....|
0000:0010|00 06 00 00 00 4d 65 6c 69 61 00 00 00 00 00 00|.....Melia......|
0000:0020|00 00 00 10 00 00 00 52 65 61 64 79 2e 20 53 65|.......Ready. Se|
0000:0030|74 2e 20 47 4f 21 00 00                        |t. GO!..        |
```

Sender = Melia
Target =
Message = 'Ready. Set. GO!'

```
0000:0000|0c 00 00 00 00 cf 0d 00 13 2c 00 30 f1 00 00 00|.........,.0....|
0000:0010|00 06 00 00 00 53 61 6d 6d 79 00 c9 0d 00 12 2c|.....Sammy.....,|
0000:0020|00 30 f1 06 00 00 00 4d 65 6c 69 61 00 0e 00 00|.0.....Melia....|
0000:0030|00 48 45 59 21 20 4e 6f 20 66 61 69 72 21 00 00|.HEY! No fair!..|
```

Sender = Sammy
Target = Melia
Message = 'HEY! No fair!'

```
0000:0000|0c 00 00 00 00 c9 0d 00 12 2c 00 30 f1 00 00 00|.........,.0....|
0000:0010|00 06 00 00 00 4d 65 6c 69 61 00 00 00 00 00 00|.....Melia......|
0000:0020|00 00 00 08 00 00 00 49 20 77 69 6e 21 21 00 00|.......I win!!..|
```

Sender = Melia
Target = 
Message = 'I win!!'

```
0000:0000|0c 00 00 00 00 cf 0d 00 13 2c 00 30 f1 00 00 00|.........,.0....|
0000:0010|00 06 00 00 00 53 61 6d 6d 79 00 c9 0d 00 12 2c|.....Sammy.....,|
0000:0020|00 30 f1 06 00 00 00 4d 65 6c 69 61 00 0d 00 00|.0.....Melia....|
0000:0030|00 59 6f 75 20 63 68 65 61 74 65 64 21 00 00 |.You cheated!..|
```

Sender = Sammy
Target = Melia
Message = 'You cheated!'

```
0000:0000|0c 00 00 00 00 c9 0d 00 12 2c 00 30 f1 00 00 00|.........,.0....|
0000:0010|00 06 00 00 00 4d 65 6c 69 61 00 00 00 00 00 00|.....Melia......|
0000:0020|00 00 00 29 00 00 00 57 61 6e 6e 61 20 72 61 63|...)...Wanna rac|
0000:0030|65 20 61 67 61 69 6e 3f 20 42 65 73 74 20 74 77|e again? Best tw|
0000:0040|6f 20 6f 75 74 20 6f 66 20 74 68 72 65 65 21 00|o out of three!.|
0000:0050|00                                             |.               |
```

Sender = Melia
Target = 
Message = 'Wanna race again? Best two out of three!'

Finally, I also managed to find a set of waypoints for Melia and Sammy. I can't guarantee I was long and close enough in Caer Darrow for these to be a complete and accurate set, but they seem to make a rough tour around the fountain and end where the two girls spawn so it looks pretty complete (and it's better than nothing for now I guess).

Melia spawns at (x y z o) = (1113.59 -2555.59 59.2532 3.50682). Her waypoints:

| Point | X | Y | Z |
| --- | --- | --- | --- |
| 1 | 1120.09 | -2547.57 | 59.2532 |
| 2 | 1111.05 | -2537.9 | 59.2532 |
| 3 | 1100.43 | -2547.73 | 59.2532 |
| 4 | 1109.6 | -2558.2 | 59.2532 |
| 5 | 1113.59 | -2555.59 | 59.2532 |
| 6 | 1113.59 | -2555.59 | 59.2532 |
| 7 | 1113.59 | -2555.59 | 59.2532 |

Sammy spawns at (x y z o) = (1111.49 -2556.4 59.2532 0.365222). Her waypoints:

| Point | X | Y | Z |
| --- | --- | --- | --- |
| 1 | 1120.72 | -2548.21 | 59.2532 |
| 2 | 1110.95 | -2538.51 | 59.2532 |
| 3 | 1100.73 | -2547.23 | 59.2532 |
| 4 | 1109.56 | -2557.59 | 59.2532 |
| 5 | 1111.49 | -2556.4 | 59.2532 |
| 6 | 1111.49 | -2556.4 | 59.2532 |

Yes, the last ones are duplicates and match their spawn points exactly. I think I've been bitten by the same bug in my tools as when I was gathering data in BRD's Manufactory: there is most likely an orientation that changes there, but I'm missing it. I'm guessing it's a part of the end conversation. I doesn't look like they are running around all the time, so this needs some scripts anyway. I still have my Spectral Essence, so one day I'll go check again to see if they are still there. But for now, this bunch old data should do.

**Comment by cala** [comment] 2015-12-23 16:29
Thank you a lot @evil-at-wow , you are like a premium goldmine and my long experience in Warcraft II: Tides of Darkness and Warcraft III: Reign of Chaos made me quite an expert in that specific field. :wink: 

> **Cala:** Hey, evil! By any chance, do you have some data about that NPC that only a handful of veteran players know about?
> **evil-at-wow:** Sure, let me some time to look into my peta-octets of sniff data and videos.
> _A few hours later_
> **evil-at-wow:** I found it. Bad news, I don't have all what you asked for.
> _Gives 95% of the requested data._
> **evil-at-wow:** Good news, after analysing the data I found a way to guess some bit of what is missing.
> _Gives out the remaining 4.95% of the data_

Take care, I'll end up having extremely high expectations! :laughing: 

Back on topic. Thank you for Illusions of Jandice Barov data.

For the Risen Aberration, this is as I feard... We are lacking of some mechanics implementation in our core. :disappointed: 

And for Sammy and Melia: this is awesome, this is exactly what I was missing. Yes, the two NPCs run around the fountain, wait for a while and do it again. They do it endlessly. This may be their curse in their afterlife. Poor children.

**Comment by Jaypy** [comment] 2016-10-10 00:16
Hey @evil-at-wow do you have a blog or anywhere one can learn about this "sniffing"? Completely amazed and interested after reading these comments. It sounds like you parse the bytes of the client? But then i dont understand how you extract correct data such as spawn points. Is that info found through the client. Or did you somehow get this data from retail clients back in the day? 

So many questions. Thanks for waking my curiousity :)

**Comment by evil-at-wow** [comment] 2016-10-15 21:07
@Jaypy I'm afraid my web presence is pretty much non-existing. So there's no blog or website that I can refer you to.

The client knows about the maps, geometry, models, textures, and some more general data (spells, areas, factions, etc, in the different DBC files), but that's pretty much it. So it knows how to render something if you tell it what models and equipment it uses, where in the world it is, what level it is, what its (current) health is, etc. The client knows how to render the animation of a boss that's casting a spell - imagine say Ragnaros smashing his hammer - if you tell it that boss is casting that particular spell, and so on. All the data that describes the actual state of the world and everything in it, is sent by the server. You won't find it in the client files.

So there are two parts in this. The first is getting the data that is sent between the client and the server. That is where I got my data: from retail servers when I was playing the game. The communication between client and server is partly encrypted though, so it's not entirely as straightforward as it may sound. The second part is making sense of all that data that the client and server exchange. That requires finding out what exactly the client does with the data it receives from the server, what it means, etc. This is mostly done by some reverse engineering of the client, and it's by far the hardest part to do. Once you know how to interpret (some of) that data, you can do what the client would do and extract the pieces of data just like the client would do. That way, you can get data for spawns, movement (waypoints), spell IDs, gossip IDs and text, quest texts etc.

I'll finish with a word of warning though: if you would seriously consider experimenting with capturing data between client and server, then know that you're putting your account at stake because it's against the EULA. For educational purposes, experiment with your own server!

**Comment by cala** [comment] 2016-12-14 10:33
For the original issue, I still have no idea. Poke @killerwife who once spoke about this on IRC, so he might give a hint about it:
>When Jandice Barov summons its illusions you should loose your target so that you have to find her. At the moment she is still your target.
>
> NPC: http://www.wowhead.com/npc=10503
>
> Sources:
> https://web.archive.org/web/20070817110742/http://wow.allakhazam.com/db/mob.html?wmob=11439
> http://wowpedia.org/Jandice_Barov_%28original%29
> http://wowdata.buffed.de/npc/Jandice-Barov-10503#comments (german)

**Comment by killerwife** [comment] 2016-12-14 10:35
Huh? Did I really? :D

**Comment by cala** [comment] 2018-01-22 21:54
Example of proper behaviour:
https://www.youtube.com/watch?v=PCbyX9KkaAM

**Closed as completed** 2018-01-22 21:56 UTC
Labels: Core / ScriptDev2, Dungeon
