### ISSUE TITLE
The Hero of the Day

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#684] opened 2014-12-20 16:58 UTC
When you're at the gossip menue und want to click on the quest, you get a wow-error. when trying it several times it is possible that the quest suddenly appears with a crazy message. Thereafter i was not able to read click on the npc and couldn't ready its name. After relogging i could click on him again but the wow-error still occured. 

Quest: http://www.wowhead.com/quest=8763
http://cl.ly/image/1r2V2M1G0A1S
http://cl.ly/image/0a21023R3X3N

**Comment by evil-at-wow** [comment] 2014-12-20 23:15
That's basically a null-pointer getting dereferenced I think. The referenced memory is at 0x04E3 (hex), which is a very low address and in particular in the first 4k that is typically made non accessible by the operating system to catch null-pointer accesses. Sounds like something gets accessed at some offset in an object that happens to be null.

Although the root cause might be a database issues (wrong data or something), I'd like to see this checked and fixed in the core too...

**Comment by cala** [comment] 2015-04-27 15:36
The data for the quest in the DB were not correct, this seems to be fixed with https://github.com/classicdb/database/commit/1047cd4d34fb70ebcbb4b67fb7db63b2251fbb7e

**Closed as completed by cala** 2015-04-27 15:36 UTC
Labels: Quest, Gossip Menu, Non-functional, Game Event
