### ISSUE TITLE
[Critter] [Minor] - Some critters are marked as 'offline'

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#239] opened 2014-02-03 03:28 UTC
Rabbits in Elwynn Forest are offline.

![critteroffline](https://f.cloud.github.com/assets/4753528/2062257/0153e2c4-8c83-11e3-914e-0de5dbdff144.png)

We noticed this with different UIs.

**Comment by cala** [comment] 2014-02-03 09:44
Surprising. I don't know what is the cause of this yet. I'll have a look at that.

**Comment by cala** [comment] 2014-02-03 10:18
After checking the database, the only significative differences between these two critters are:
- rabbit is skinnable (chicken is not)
- chicken is involved in quest (rabbit is not)
- rabbit is immune to charm (chicken is not)

None of them should trigger such behavior.
Did you try without any GUI? I suspect the switch being made by the HP number (1HP may be handled as 'dead' by many GUI, greying it out like dead or offline)

**Comment by ghost** [comment] 2014-02-03 13:51
I agree with cala this seems an add-on thing then the game. But it should be noted that I'm fairly certain all critters had/have 1hp and no loot.{not even sparklies}

**Comment by cala** [comment] 2014-02-07 11:01
In fact, according to http://www.wowwiki.com/Critters , some critters can have more than 1 HP (and I clearly remember that from Classic). Some of them could also be skinned. They do not have loot however, like you said.

Back to the main topic of this issue, I will run a test changing the hit points of a critter (the chicken for instance) to 1 and see if this happens.

**Comment by Tobschinski** [comment] 2014-02-08 12:39
I have already started doing a list of every critter out there, with corrected health points. I would rather do something useful, like testing dungeons and stuff, but for now, I lack the needed powers to solo it. If anyone in here know who I have to convince to get these, please let me know.

Back to topic, I have gone through my unitframes' code and found the line
   or not UnitIsConnected(self.unit) or (currValue == 1 and maxValue == 1) ) then 

Changing it solves the problem, so it was my mistake, but I have never noticed anything like that back in vanilla or on other private servers, my bad.

What in fact is broken about critters other than being lootable, is that you generate 0 rage on them. Would that be a core issue? I will add it to its tracker then.

**Comment by ghost** [comment] 2014-02-08 15:26
You can always just localhost a copy of the server, that is how I did all the dungeon testing I did.

**Comment by Tobschinski** [comment] 2014-02-08 15:35
Unfortunately, that is not possible right now.

**Comment by cala** [comment] 2014-02-10 14:49
> What in fact is broken about critters other than being lootable, is that you generate 0 rage on them. Would that be a core issue? I will add it to its tracker then.

Currently, there is only one critter that drops something and this is intended because it is involved in a quest (creature 3444 Dig Rat). The other critters do probably have the "sparkles" effect once killed, but their corpse is empty. I'm not sure it was the case in retail, but if we want to fix this, this can only be done by core.

Regarding the rage generation, I'm only 98% sure this is core related. Maybe some proc flag is missing somewhere in DB.

**Comment by cala** [comment] 2014-02-20 14:37
After peering into core codes, I confirm the missing rage regeneration is 100% a core issue.
Damage is handled in Unit.cpp by `uint32 Unit::DealDamage` where there is a special case for critters:

``` c++
// no xp,health if type 8 /critters/
    if (pVictim->GetTypeId() == TYPEID_UNIT && pVictim->GetCreatureType() == CREATURE_TYPE_CRITTER)
    {
        // TODO: fix this part
        // Critter may not die of damage taken, instead expect it to run away (no fighting back)
        // If (this) is TYPEID_PLAYER, (this) will enter combat w/victim, but after some time, automatically leave combat.
        // It is unclear how it should work for other cases.

        DEBUG_FILTER_LOG(LOG_FILTER_DAMAGE, "DealDamage critter, critter dies");

        ((Creature*)pVictim)->SetLootRecipient(this);

        JustKilledCreature((Creature*)pVictim, NULL);
        pVictim->SetHealth(0);

        return damage;
    }
```

As you can see, this code returns without rewarding rage. Rage regeneration is rewarded in the same function, but later:

``` c++
// Rage from Damage made (only from direct weapon damage)
    if (cleanDamage && damagetype == DIRECT_DAMAGE && this != pVictim && GetTypeId() == TYPEID_PLAYER && getPowerType() == POWER_RAGE && cleanDamage->attackType != RANGED_ATTACK)
        ((Player*)this)->RewardRage(damage, true);
```

Thus, we should add to the first part:

``` diff
// no xp,health if type 8 /critters/
    if (pVictim->GetTypeId() == TYPEID_UNIT && pVictim->GetCreatureType() == CREATURE_TYPE_CRITTER)
    {
        // TODO: fix this part
        // Critter may not die of damage taken, instead expect it to run away (no fighting back)
        // If (this) is TYPEID_PLAYER, (this) will enter combat w/victim, but after some time, automatically leave combat.
        // It is unclear how it should work for other cases.

        DEBUG_FILTER_LOG(LOG_FILTER_DAMAGE, "DealDamage critter, critter dies");

        // Rage from Damage made (only from direct weapon damage)
    if (cleanDamage && damagetype == DIRECT_DAMAGE && this != pVictim && GetTypeId() == TYPEID_PLAYER && getPowerType() == POWER_RAGE && cleanDamage->attackType != RANGED_ATTACK)
        ((Player*)this)->RewardRage(damage, true);

        ((Creature*)pVictim)->SetLootRecipient(this);

        JustKilledCreature((Creature*)pVictim, NULL);
        pVictim->SetHealth(0);

        return damage;
    }
```

I also think that `((Creature*)pVictim)->SetLootRecipient(this);` should only be set if pVictim is entry 3444 (Dig Rat).

**Comment by cala** [comment] 2014-02-20 14:44
Critter versus rage issue opened in core https://github.com/cmangos/issues/issues/231. I close this one. Thanks all.

**Closed as completed by cala** 2014-02-20 14:44 UTC
Labels: NPC, Enhancement, Core / ScriptDev2
