### ISSUE TITLE
Nightlash

### ISSUE THREAD

**Issue by katz1** [classicdb/database#846] opened 2016-05-20 16:53 UTC
The npc Nightlash (1983) has a spell called Spirit Steal (3477), which leeches 1000 hit points from the target.
She is currently using this on the player, which pretty much one hits anything around that level making her quest fairly impossible.
According to the comments (http://db.vanillagaming.org/?npc=1983#wh-comments), she should be using this spell only to sacrifice nearby friendly gnolls to heal herself.

**Comment by Xentr0** [comment] 2016-05-23 20:39
I read this and thought it was an interesting issue so I tried to replicate it and found that this was indeed the case.
Then I went ahead and checked the AI databases for the spell usage and it is filled out correctly. Correctly in this case means that it uses the same values other monster use to check if allies who are close by are injured to decide if it should cast a spell on them. Think healers who will heal an injured ally, many humanoid monsters have this behavior. However, I think the behavior of this spell was modified somewhere in the core files (not sure about this) since the described behavior would mean she would be able to kill herself (like monsters who heal allies but can also heal themselves). Not 100% sure about this, but it's my best guess from what I found in the DB.

**Comment by cala** [comment] 2016-05-24 08:12
Possibly the logic of the AI script is wrong here because, basically, the NPC would cast the leech spell on itself and not on nearby friendlies. And from what I read in the core code, this could lead to unexpected behaviours because this case is not handled (and I don't think it needs to be handled).
I'll see if we can do it otherwise.
Looks like someone did not test the script after writing it...

**Comment by cala** [comment] 2016-05-24 14:52
Also, Nightlash is missing its/her texts: http://www.wowhead.com/npc=1983/nightlash#comments:id=729557

Related:
https://github.com/cmangos/issues/issues/775

**Comment by Almightie** [comment] 2016-06-18 17:35
Tried moving her AI to scriptdev, but calling the spell on a (for nightlash) friendly target also causes surrounding targets (including me if close) to take the 1k damage. Looks like an aoe effect?
Also, the EventAI Target Types don't seem to have been set up for targetting a random allie, I guess that TargetTypes would need to be expanded.

**Comment by cala** [comment] 2017-01-17 15:41
Closed by https://github.com/cmangos/mangos-classic/commit/e9def84f41d355317e351490052ceba4791414db

**Closed as completed by cala** 2017-01-17 15:41 UTC
Labels: NPC, Enhancement, Core / ScriptDev2, ACID
