### ISSUE TITLE
Frostmane Headhunter missing projectile model

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#103] opened 2013-08-11 19:50 UTC
Frostmane Headhunter missing projectile model.

Area: Dun Morogh, Frostmane Hold
How to replicate the bug: Get attacked by a Frostmane headhunter, and look closely on what he throws.
What happens: The Frostmane Headhunter throws a blue and white box.
What should happen: The Frostmane Headhunter throws a spear.

**Comment by cala** [comment] 2013-08-11 20:02
Almost all NPC projectiles use this placeholder model. I agree this should be fixed, but as the game works as intended (this is just cosmetic), the fix will probably wait unless it is very quick/easy to fix (don't know, didn't look at yet).

**Comment by dope250** [comment] 2013-08-11 20:02
Edit: Ah thanks cala, was to slow. Sorry ;)

Can confirm. Got an similiar Error with "Defias Smuggler" ( http://old.wowhead.com/npc=95/ ) in Westfall. They should throw dagger not boxes, I guess.
![wowscrnshot_081113_014103](https://f.cloud.github.com/assets/4180129/944564/d7685612-02c0-11e3-93ee-25d82b0ad85b.jpg)

**Comment by cala** [comment] 2013-08-11 20:54
For information: the projectile model is correct on WotLK (with UDB 406), just tested right now. Might come from core too, though.

**Comment by cala** [comment] 2014-06-18 22:57
Closed by https://github.com/classicdb/database/commit/d1a831468052209a280e266e47721200fdee5060

**Closed as completed by cala** 2014-06-18 22:57 UTC
Labels: NPC, Enhancement
