### ISSUE TITLE
Signet of Expertise

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#743] opened 2015-02-17 09:53 UTC
When you use the Signet of Expertise it sould create a Hammer of Expertise. The signet has a cooldown of 3 hours and the hammer lasts for 1 hour. 

Bugs:
The signet disappears when you use it.
You don't get the hammer.

http://www.wowhead.com/item=8703/signet-of-expertise
http://www.wowhead.com/item=8708/hammer-of-expertise

**Comment by ghost** [comment] 2015-02-20 21:21
Make sure you are up to date with all of the updates, as it works fine for me.

**Comment by cala** [comment] 2015-02-24 23:01
> The signet disappears when you use it.

I guess it was equipped on the character instead. This item is a trinket: it must be equipped to work.

Closing here, the item works as intended. Thank you.

**Closed as completed by cala** 2015-02-24 23:01 UTC
Labels: Item, Enhancement, Spell
